### ISSUE TITLE
有一些问题回复的时候会偶尔出现php代码

### ISSUE THREAD

**Issue by jevonszmx** [qiayue/php-openai-gpt-stream-chat-api-webui#1]
我问“今天是哪一天？”的时候，系统出现了2次php源码

<?php echo date(

闪了一下就没了，直接句号结束了。

![截屏2023-03-26 02 05 58](https://user-images.githubusercontent.com/1784463/227734128-0c885299-d4ed-444c-aa46-576edbfb8d6d.jpg)

**Comment by qiayue** [comment]
如果你是在演示站遇到这个问题的话，是因为我演示站的 system 设定导致模型返回了 php 代码告诉你怎么打印当天日期，而且返回的代码前后没加 '`' 符号把代码扩起来，导致 markd 解析时自动给 \<?php 前面加 html 的注释了。
现在演示站修改了 system 的设定，不会出现这个问题了，算是治标了。但是为什么那个 system 会导致模型直接返回 php 代码，很有意思，我去研究下。
{"time":"2023-03-26 06:34:02","content":"\u7b54\uff1a "}
{"time":"2023-03-26 06:34:03","content":"今"}
{"time":"2023-03-26 06:34:03","content":"天"}
{"time":"2023-03-26 06:34:03","content":"是"}
{"time":"2023-03-26 06:34:03","content":" \<?"}
{"time":"2023-03-26 06:34:03","content":"php"}
{"time":"2023-03-26 06:34:03","content":" echo"}
{"time":"2023-03-26 06:34:03","content":" date"}
{"time":"2023-03-26 06:34:03","content":"('"}
{"time":"2023-03-26 06:34:03","content":"Y"}
{"time":"2023-03-26 06:34:03","content":"年"}
{"time":"2023-03-26 06:34:03","content":"m"}
{"time":"2023-03-26 06:34:03","content":"月"}
{"time":"2023-03-26 06:34:03","content":"d"}
{"time":"2023-03-26 06:34:03","content":"日"}
{"time":"2023-03-26 06:34:03","content":"');?>"}
{"time":"2023-03-26 06:34:03","content":"。"}
Connection closed
